### ISSUE TITLE
Please allow changing order by format

### ISSUE THREAD

**Issue by paladox** [dominic-p/videojs-resolution-selector#35]
Hi please allow us to do it by order for example webm and ogv should be like this

webm

360p

480p

and so on

and ogv should look like

ogv

360p

480p

**Comment by dominic-p** [comment]
I'm not really understanding what you are asking here. Could you provide an example of what you are hoping to achieve?

**Comment by paladox** [comment]
Ok an example is for example 

webm 

360p

460p

so that the resolutions are under there correct video or audio format.

**Comment by dominic-p** [comment]
Umm, that just looks like your original post again. Are you saying that in the menu that is generated, you want the resolution options broken down by file type? So you user can choose either the 360p webm file or the 360p mp4 file?

**Comment by paladox** [comment]
Yes but like currently it dosent say webm only shows resolutions it would be greate if the resolutions were organised into the formats they are for.

**Comment by dominic-p** [comment]
Ok, I think I understand what you're looking for now. I don't think I want to head down that road with this plugin. As a user, I don't really care what the file format is, I just want the video to play. So, I want to keep the options as simple as possible on this plugin.

I'm going to go ahead and close this for now, but feel free to add any other thoughts you had.

**Comment by paladox** [comment]
Ok but what about adding a option.

**Comment by dominic-p** [comment]
Probably not given the added complexity it would bring to the project. For example, there would probably need to be some way to determine if the browser supports a given file type (otherwise the UX would be pretty bad when the user tries to select a resolution that his browser doesn't support). So we're left with reinventing some core Video.js functionality or trying access low level details about the files.
